apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: audiobookshelf-public
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`audiobookshelf.fredericlefebvrecote.com`)
      kind: Rule
      services:
        - name: audiobookshelf
          port: 80
  tls:
    certResolver: letsencrypt
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: audiobookshelf
#   namespace: audiobookshelf
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: audiobookshelf.fredericlefebvrecote.com
#       http:
#         paths:
#           - backend:
#               service:
#                 name: audiobookshelf
#                 port:
#                   number: 3005
#             path: /
#             pathType: Prefix
#
