apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:8/+2dOlozo4gx7tghQDWawRkrwudCejM6+ZD9pHo+Hup6WzxMqcUuw==,iv:mjphzMDfewyorcY8RWNT9EtrIPqCBtkj1G27kYlBHM4=,tag:kFHFtVlAYj6Vg01GC58P6A==,type:str]
sops:
    age:
        - recipient: age154p5ddddkvhftah6vv2y4kdpgkhaukgjnkrfdn8rgkugugec5chqqc87ey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bXdvMDRqZHlNKzM1V1Rs
            Mmgrd1JGa093bWZITXhZNWY1bi84b2d4TFJRCjF5QlUxcUhxMjRlK0NjUmM3NDVJ
            MHQzSjhFUENzeTRnV2wzZEtjSTN4MmcKLS0tIHVKSndXdFowUERsR25GeGFmN0pF
            a3hxT2lUTXc4ajA0dndWdHF4cjRSQXMKa7kByGLauQpekA2+IhI+AyEOtLF0FsZG
            yXN8X+lzn3bCMaxVNpVCiU0gAEmiWlnEWH0QJvm5BsV4qXKuWrEI1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T15:56:31Z"
    mac: ENC[AES256_GCM,data:etWu6GI8X6MQh2+G436PGgPj7gvvwtNTGIjyg+7q421j1PmDTfCqCNJ5XQZ4Q2E66NZt3yOs13pUtMBNxyz5guSsNC0spDG10P/xO61P95tE0oNGapkwUwsbX+npIr2qH8MKzwxEahoVj55U5xRfp0xEBrLG8GHWie7VuAdpGhs=,iv:Ymfp3fmPUIhxQU5x3yfBqsP/dD8KAZ5GTFaPpeG1xs8=,tag:wWumlNqsGpZh6f8RZMJCHg==,type:str]
    encrypted_regex: ^(data|stringData)
    version: 3.11.0
