apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf

    restartPolicy: always
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 80

          volumeMounts:
            - mountPath: "/audiobooks"
              name: audiobooks
            
            - mountPath: "/podcasts"
              name: podcasts

            - mountPath: "/config"
              name: config

            - mountPath: "/metadata"
              name: metadata

      volumes:
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-pvc

        - name: podcasts
          persistentVolumeClaim:
            claimName: podcasts-pvc

        - name: config
          persistentVolumeClaim:
            claimName: config-pvc

        - name: metadata
          persistentVolumeClaim:
            claimName: metadata-pvc
