apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf

    restartPolicy: always
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
        - name: init-volumes
          image: busybox:1.37
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              set -eu

              for d in /audiobooks /podcasts /config /metadata; do
                echo "Fixing permissions on $d"
                mkdir -p "$d"
                chown -R 1000:1000 "$d"
                chmod -R u+rwX,g+rwX "$d"
              done
          volumeMounts:
            - name: audiobooks
              mountPath: /audiobooks
            - name: podcasts
              mountPath: /podcasts
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 80

          volumeMounts:
            - mountPath: "/audiobooks"
              name: audiobooks

            - mountPath: "/podcasts"
              name: podcasts

            - mountPath: "/config"
              name: config

            - mountPath: "/metadata"
              name: metadata

      volumes:
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-pvc

        - name: podcasts
          persistentVolumeClaim:
            claimName: podcasts-pvc

        - name: config
          persistentVolumeClaim:
            claimName: config-pvc

        - name: metadata
          persistentVolumeClaim:
            claimName: metadata-pvc
